In [1]:
from llmfoundry.models.hf import ComposerHFT5
import torch
from transformers import T5Tokenizer, AutoTokenizer, T5TokenizerFast, PreTrainedTokenizerFast, AutoConfig
from chronos.chronos import ChronosConfig, ChronosTokenizer, ChronosModel, MeanScaleUniformBins

/mnt/workdisk/kushal/llm-foundry/llmfoundry-venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [20]:
%pip install git+https://github.com/amazon-science/chronos-forecasting.git

  Cloning https://github.com/amazon-science/chronos-forecasting.git to /tmp/pip-req-build-kst7mi0l
  Running command git clone --filter=blob:none --quiet https://github.com/amazon-science/chronos-forecasting.git /tmp/pip-req-build-kst7mi0l
  Resolved https://github.com/amazon-science/chronos-forecasting.git to commit d2e0c9d6d57878ebf5af62c1ad3a12b2eb52175a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Note: you may need to restart the kernel to use updated packages.


In [2]:
model = ComposerHFT5(tokenizer = T5Tokenizer.from_pretrained("google-t5/t5-small"), # PreTrainedTokenizerBase
        pretrained_model_name_or_path = 'google-t5/t5-small', # str
        pretrained = True, # Optional[bool] = True
        trust_remote_code = True, # bool = True
        use_auth_token = False, # bool = False
        config_overrides = None, # Optional[Mapping] = None
        init_device = 'cpu', # str = 'cpu'
        additional_train_metrics = None, # Optional[List] = None
        name = 't5-small', #: Optional[str] = None
)
# tokenizer: https://huggingface.co/docs/transformers/en/model_doc/t5#transformers.T5Tokenizer
# pretrained model: https://huggingface.co/google-t5/t5-small

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/mnt/workdisk/kushal/llm-foundry/llmfoundry/utils/warnings.py:89: ExperimentalWarning: ComposerHFT5 is experimental and may change with future versions.
  warnings.warn(ExperimentalWarning(feature_name))
/usr/lib/python3/dist-packages/transformers/models/auto/configuration_auto.py:913: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  w

# Testing model keys with `torch.load()`

In [34]:
model_5 = torch.load('/mnt/workdisk/kushal/llm-foundry/scripts/output/t5-small-interactive-MWt1uQ/ep0-ba5-rank0.pt')
model_10 = torch.load('/mnt/workdisk/kushal/llm-foundry/scripts/output/t5-small-interactive-MWt1uQ/ep0-ba10-rank0.pt')

In [35]:
print(model_5.keys())
print(model_10.keys())

dict_keys(['state', 'rng'])
dict_keys(['state', 'rng'])


In [36]:
print(model_5['state'].keys())
print(model_10['state'].keys())

dict_keys(['model', 'optimizers', 'schedulers', 'algorithms', 'callbacks', 'scaler', 'timestamp', 'rank_zero_seed', 'run_name', 'dataset_state', 'integrations', 'metadata'])
dict_keys(['model', 'optimizers', 'schedulers', 'algorithms', 'callbacks', 'scaler', 'timestamp', 'rank_zero_seed', 'run_name', 'dataset_state', 'integrations', 'metadata'])


In [37]:
print(model_5['state']['model']['model.lm_head.weight'])
print(model_10['state']['model']['model.lm_head.weight'])

tensor([[ -2.0156,   0.2237,  -7.0937,  ...,  -0.3535,   2.6407,  -2.8907],
        [ 12.6250,   8.1875, -11.6250,  ...,   7.9375,  -7.3125,   0.9454],
        [ -8.7500,   7.1875,  27.8750,  ..., -26.7500,   0.8554,  -1.5157],
        ...,
        [-25.2500, -28.5000, -17.2500,  ..., -17.7500,  -5.2500,  27.3750],
        [-25.5000, -29.3750, -18.2500,  ..., -17.7500,  -4.8125,  27.7500],
        [-26.7500, -28.3750, -17.8750,  ..., -18.5000,  -7.0000,  27.6250]],
       device='cuda:0')
tensor([[ -2.0156,   0.2237,  -7.0937,  ...,  -0.3535,   2.6407,  -2.8907],
        [ 12.6249,   8.1874, -11.6249,  ...,   7.9374,  -7.3125,   0.9454],
        [ -8.7500,   7.1875,  27.8750,  ..., -26.7500,   0.8554,  -1.5157],
        ...,
        [-25.2500, -28.5000, -17.2500,  ..., -17.7500,  -5.2500,  27.3750],
        [-25.5000, -29.3750, -18.2500,  ..., -17.7500,  -4.8125,  27.7500],
        [-26.7500, -28.3750, -17.8750,  ..., -18.5000,  -7.0000,  27.6250]],
       device='cuda:0')


In [19]:
model['rng'][0].keys()

dict_keys(['python', 'numpy', 'torch', 'cuda'])

In [27]:
model['rng'][0]['python']

(3,
 (2147483648,
  3170634271,
  2035982193,
  859452641,
  567914427,
  1526164465,
  2652430106,
  3549929089,
  15118359,
  3474503331,
  2204943320,
  561448987,
  3853569459,
  2672065287,
  1054713599,
  1216758441,
  120103628,
  4113501092,
  75122332,
  3635752974,
  2922626534,
  3504939389,
  4262355907,
  2016019026,
  3786930039,
  3546084902,
  2881831452,
  3911063105,
  57826278,
  1556482840,
  3416069416,
  412658993,
  579477156,
  3541357095,
  1351528459,
  1468409607,
  3336715696,
  4213747970,
  279014888,
  4252844498,
  2849747261,
  3989422257,
  1944182354,
  275339130,
  2315189997,
  1571994218,
  3156519093,
  1534727095,
  3185519333,
  1646492138,
  3720201960,
  2751641298,
  3708784016,
  2709587081,
  152700890,
  3997662882,
  3047081649,
  591435452,
  3678047174,
  3538079613,
  3298226431,
  3141372844,
  3578240196,
  3027385354,
  836073235,
  872312709,
  1897193585,
  1148545581,
  836544537,
  579720199,
  237082603,
  2065715651,
  1231944

In [25]:
model['rng'][0]['numpy']

('MT19937',
 array([        17,  746594230, 3313428688,  930072130, 4093676046,
        3497159718,  168261535, 1297041602,  797773815, 3824384892,
         815771685,  289885092,  974625728, 3488232141, 2822261076,
        3335386365, 2186253894, 3433868517, 3941682384, 4044700242,
        1036802825,  127318946,  575650048, 1114963223,  120758214,
        3571711799, 3958539166, 3026711052, 1408105890,  756436076,
        1604711098,  310105830, 2032590558, 3316925724, 1895160925,
        4201720943,  643846848, 4085868005, 1845971428, 4037981312,
        2803651287,  911452978, 4227747044,  281867854, 4107201266,
        1777642050, 2826569629,  261232874, 3126791810, 3418568881,
        2184880236, 2348689817, 3334954331, 3406031853,  223376156,
        1142646339,  743877186, 1595702851,  295510596, 2855332111,
         761194333, 1070402798, 2857596964,  793034045, 1477398097,
        3542267345, 1891442204, 3196413620,  630385682, 2143995231,
        4231081052,  448682178, 2951

In [22]:
model['rng'][0]['cuda']

tensor([ 17,   0,   0,   0,   0,   0,   0,   0, 192,  79,   4,   0,   0,   0,
          0,   0], dtype=torch.uint8)

# Testing `amazon/chronos-t5-small`

## Loading in `google-t5/t5-small`

In [9]:
tokenizer = AutoTokenizer.from_pretrained('google-t5/t5-small')
type(tokenizer)

transformers.models.t5.tokenization_t5_fast.T5TokenizerFast

In [10]:
tokenizer = T5TokenizerFast.from_pretrained('google-t5/t5-small')
type(tokenizer)

transformers.models.t5.tokenization_t5_fast.T5TokenizerFast

In [14]:
tokenizer = T5Tokenizer.from_pretrained('google-t5/t5-small')
type(tokenizer)

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


transformers.models.t5.tokenization_t5.T5Tokenizer

In [11]:
tokenizer = PreTrainedTokenizerFast.from_pretrained('google-t5/t5-small')
type(tokenizer)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'T5Tokenizer'. 
The class this function is called from is 'PreTrainedTokenizerFast'.


transformers.tokenization_utils_fast.PreTrainedTokenizerFast

In [2]:
from transformers import AutoTokenizer

# Load a pre-trained tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# Tokenize a single sentence
encoded_input = tokenizer("Hello, how are you?")
print(type(encoded_input))
print(encoded_input)

<class 'transformers.tokenization_utils_base.BatchEncoding'>
{'input_ids': [101, 7592, 1010, 2129, 2024, 2017, 1029, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}


In [3]:
# Tokenize a batch of sentences
batch_sentences = ["Hello, how are you?", "I am fine, thank you."]
batch_encoded_input = tokenizer(batch_sentences, padding=True, truncation=True, return_tensors="pt")

# Accessing BatchEncoding properties
input_ids = batch_encoded_input["input_ids"]
attention_mask = batch_encoded_input["attention_mask"]

print(type(batch_encoded_input))
print(batch_encoded_input)
print(input_ids)
print(attention_mask)

<class 'transformers.tokenization_utils_base.BatchEncoding'>
{'input_ids': tensor([[ 101, 7592, 1010, 2129, 2024, 2017, 1029,  102,    0],
        [ 101, 1045, 2572, 2986, 1010, 4067, 2017, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])}
tensor([[ 101, 7592, 1010, 2129, 2024, 2017, 1029,  102,    0],
        [ 101, 1045, 2572, 2986, 1010, 4067, 2017, 1012,  102]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])


## Incorrectly loading in `amazon/chronos-t5-small`

In [13]:
tokenizer = AutoTokenizer.from_pretrained("amazon/chronos-t5-small")

OSError: Can't load tokenizer for 'amazon/chronos-t5-small'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'amazon/chronos-t5-small' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.

In [16]:
tokenizer = T5TokenizerFast.from_pretrained("amazon/chronos-t5-small")

OSError: Can't load tokenizer for 'amazon/chronos-t5-small'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'amazon/chronos-t5-small' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.

In [3]:
tokenizer = T5Tokenizer.from_pretrained("amazon/chronos-t5-small")

OSError: Can't load tokenizer for 'amazon/chronos-t5-small'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'amazon/chronos-t5-small' is the correct path to a directory containing all relevant files for a T5Tokenizer tokenizer.

In [17]:
tokenizer = PreTrainedTokenizerFast.from_pretrained("amazon/chronos-t5-small")

OSError: Can't load tokenizer for 'amazon/chronos-t5-small'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'amazon/chronos-t5-small' is the correct path to a directory containing all relevant files for a PreTrainedTokenizerFast tokenizer.

## Correctly loading in `amazon/chronos-t5-small`

In [12]:
config = AutoConfig.from_pretrained('amazon/chronos-t5-small')
print(type(config))

chronos_config = ChronosConfig(**config.chronos_config)
print(type(chronos_config))

tokenizer = chronos_config.create_tokenizer()
print(type(tokenizer))

<class 'transformers.models.t5.configuration_t5.T5Config'>
<class 'chronos.chronos.ChronosConfig'>
<class 'chronos.chronos.MeanScaleUniformBins'>


In [3]:
# tokenizer = AutoTokenizer.from_pretrained('amazon/chronos-t5-small')
tokenizer = AutoTokenizer.from_pretrained('google-t5/t5-small')
print(type(tokenizer))

<class 'transformers.models.t5.tokenization_t5_fast.T5TokenizerFast'>


# Test out `ChronosPipeline`

In [4]:
# taken straight from chronos-forecasting/src/chronos/chronos.py

import warnings
from dataclasses import dataclass
from typing import Any, Dict, List, Literal, Optional, Tuple, Union

# import chronos
import chronos.chronos as chronos
import torch
import torch.nn as nn
from transformers import (
    AutoConfig,
    AutoModelForCausalLM,
    AutoModelForSeq2SeqLM,
    GenerationConfig,
    PreTrainedModel,
)

In [18]:
@dataclass
class ChronosPipeline:
    """
    A ``ChronosPipeline`` uses the given tokenizer and model to forecast input time series. Use the ``from_pretrained`` class method to load serialized models. Use the ``predict`` method to get forecasts.

    Parameters
    ----------
    tokenizer
        The tokenizer object to use.
    model
        The model to use.
    """

    tokenizer: ChronosTokenizer
    model: ChronosModel

    def _prepare_and_validate_context(
        self, context: Union[torch.Tensor, List[torch.Tensor]]
    ):
        if isinstance(context, list):
            context = left_pad_and_stack_1D(context)
        assert isinstance(context, torch.Tensor)
        if context.ndim == 1:
            context = context.unsqueeze(0)
        assert context.ndim == 2

        return context

    @torch.no_grad()
    def embed(
        self, context: Union[torch.Tensor, List[torch.Tensor]]
    ) -> Tuple[torch.Tensor, Any]:
        """
        Get encoder embeddings for the given time series.

        Parameters
        ----------
        context
            Input series. This is either a 1D tensor, or a list of 1D tensors, or a 2D tensor whose first dimension is batch. In the latter case, use left-padding with ``torch.nan`` to align series of different lengths.

        Returns
        -------
        embeddings, tokenizer_state
            A tuple of two tensors: the encoder embeddings and the tokenizer_state, e.g., the scale of the time series in the case of mean scaling. The encoder embeddings are shaped (batch_size, context_length, d_model) or (batch_size, context_length + 1, d_model), 
            where context_length is the size of the context along the time axis if a 2D tensor was provided or the length of the longest time series, if a list of 1D tensors was provided, and the extra 1 is for EOS.
        """
        context_tensor = self._prepare_and_validate_context(context=context)
        token_ids, attention_mask, tokenizer_state = (
            self.tokenizer.context_input_transform(context_tensor)
        )
        embeddings = self.model.encode(
            input_ids=token_ids.to(self.model.device),
            attention_mask=attention_mask.to(self.model.device),
        ).cpu()
        return embeddings, tokenizer_state

    def predict(
        self,
        context: Union[torch.Tensor, List[torch.Tensor]],
        prediction_length: Optional[int] = None,
        num_samples: Optional[int] = None,
        temperature: Optional[float] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        limit_prediction_length: bool = True,
    ) -> torch.Tensor:
        """
        Get forecasts for the given time series.

        Parameters
        ----------
        context
            Input series. This is either a 1D tensor, or a list of 1D tensors, or a 2D tensor whose first dimension is batch. In the latter case, use left-padding with ``torch.nan`` to align series of different lengths.
        prediction_length
            Time steps to predict. Defaults to what specified in ``self.model.config``.
        num_samples
            Number of sample paths to predict. Defaults to what specified in ``self.model.config``.
        temperature
            Temperature to use for generating sample tokens. Defaults to what specified in ``self.model.config``.
        top_k
            Top-k parameter to use for generating sample tokens. Defaults to what specified in ``self.model.config``.
        top_p
            Top-p parameter to use for generating sample tokens. Defaults to what specified in ``self.model.config``.
        limit_prediction_length
            Force prediction length smaller or equal than the built-in prediction length from the model. True by default. When true, fail loudly if longer predictions are requested, otherwise longer predictions are allowed.

        Returns
        -------
        samples
            Tensor of sample forecasts, of shape (batch_size, num_samples, prediction_length).
        """
        context_tensor = self._prepare_and_validate_context(context=context)

        if prediction_length is None:
            prediction_length = self.model.config.prediction_length

        if prediction_length > self.model.config.prediction_length:
            msg = (
                f"We recommend keeping prediction length <= {self.model.config.prediction_length}. "
                "The quality of longer predictions may degrade since the model is not optimized for it. "
            )
            if limit_prediction_length:
                msg += "You can turn off this check by setting `limit_prediction_length=False`."
                raise ValueError(msg)
            warnings.warn(msg)

        predictions = []
        remaining = prediction_length

        while remaining > 0:
            token_ids, attention_mask, scale = self.tokenizer.context_input_transform(
                context_tensor
            )
            samples = self.model(
                token_ids.to(self.model.device),
                attention_mask.to(self.model.device),
                min(remaining, self.model.config.prediction_length),
                num_samples,
                temperature,
                top_k,
                top_p,
            )
            prediction = self.tokenizer.output_transform(
                samples.to(scale.device), scale
            )

            predictions.append(prediction)
            remaining -= prediction.shape[-1]

            if remaining <= 0:
                break

            context_tensor = torch.cat(
                [context_tensor, prediction.median(dim=1).values], dim=-1
            )

        return torch.cat(predictions, dim=-1)

    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        """
        Load the model, either from a local path or from the HuggingFace Hub. Supports the same arguments as ``AutoConfig`` and ``AutoModel`` from ``transformers``.
        """

        config = AutoConfig.from_pretrained(*args, **kwargs)
        print(f'type(config) == {type(config)}')

        assert hasattr(config, "chronos_config"), "Not a Chronos config file"

        chronos_config = ChronosConfig(**config.chronos_config)
        print(f'type(chronos_config) == {type(chronos_config)}')

        if chronos_config.model_type == "seq2seq":
            inner_model = AutoModelForSeq2SeqLM.from_pretrained(*args, **kwargs)
        else:
            assert config.model_type == "causal"
            inner_model = AutoModelForCausalLM.from_pretrained(*args, **kwargs)

        # ADDED THIS LINE
        tokenizer = chronos_config.create_tokenizer()
        print(f'type(tokenizer) == {type(tokenizer)}')
        
        print(cls, type(cls))
        print(args)
        print(kwargs)
        
        return cls(
            tokenizer=tokenizer, # original: chronos_config.create_tokenizer()
            model=ChronosModel(config=chronos_config, model=inner_model),
        )

In [19]:
pipeline = ChronosPipeline.from_pretrained(
    "amazon/chronos-t5-small",
    device_map="cpu",
    torch_dtype=torch.bfloat16,
)
type(pipeline)

type(config) == <class 'transformers.models.t5.configuration_t5.T5Config'>
type(chronos_config) == <class 'chronos.chronos.ChronosConfig'>
type(tokenizer) == <class 'chronos.chronos.MeanScaleUniformBins'>
<class '__main__.ChronosPipeline'> <class 'type'>
('amazon/chronos-t5-small',)
{'device_map': 'cpu', 'torch_dtype': torch.bfloat16}


__main__.ChronosPipeline

In [23]:
config = AutoConfig.from_pretrained(
    "amazon/chronos-t5-small",
    device_map="cpu",
    torch_dtype=torch.bfloat16,
)
tokenizer = T5TokenizerFast.from_pretrained(config.name_or_path)

OSError: Can't load tokenizer for 'amazon/chronos-t5-small'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'amazon/chronos-t5-small' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.

In [1]:
config.name_or_path

NameError: name 'config' is not defined